### ISSUE TITLE
Agregar indicadores basado en API Localbitcoins

### ISSUE THREAD

**Issue by chebetos** [btcven/api#11]
Últimos intercambios: https://localbitcoins.com/bitcoincharts/VEF/trades.json 
Libro de Órdenes: https://localbitcoins.com/bitcoincharts/VEF/orderbook.json

Y en base a estos crear estadísticas como la media de últimos N minutos, horas, días, semanas, meses.
Y si es posible gráficas, y un ticker como el de btcquote.

Conozco de php, así que si quieres puedo intentar hacer algunas cosas y hacerte los pull request.

**Comment by rdymac** [comment]
Ya se estaba usando en producción el orderbook de LocalBitcoins. Ahora está disponible en el nuevo código en este repo.
