### ISSUE TITLE
Innecesario calculo del valor BTC/EUR

### ISSUE THREAD

**Issue by lcamacho** [btcven/api#14]
Por algun motivo se vuelve a calcular el precio del BTC/EUR aun cuando coindesk ya envia este precio.

https://github.com/btcven/api/blob/8292679ab4b635e0fecf8560d5be0da7d1e0c243/coin/bitcoin.php#L28

**Comment by rdymac** [comment]
Resuelto en https://github.com/btcven/api/issues/15
