### ISSUE TITLE
Agregar BTC/GBP y BTC/CNY

### ISSUE THREAD

**Issue by lcamacho** [btcven/api#15]
La v2 del api coindesk ahora da el valor BTC/CNY, igualmente se deberia agregar el BTC/GBP para mostrar toda la informacion q nos brinda coindesk.

**Comment by rdymac** [comment]
BTCGBP ha sido añadido aquí: https://github.com/btcven/api/commit/55fbd0ad7af88d7b5a8f81d8e3e653ab6faba982

BTCCNY no será tomado en cuenta en esta versión de la API, por el momento.
